In [1]:
import numpy as np

In [2]:
#1[2]
a = np.arange(1,11)
b = np.arange(1,11)
arr = np.multiply.outer(a,b) 
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [3]:
#2[2]
small_arr = arr[3:7, 3:7]

In [4]:
#3[2]
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
#4[2]
def isEven(a1, a2):
  if a1 % 2 == 0 and a2 % 2 == 0:
    return True
  else:
    return False

result = np.vectorize(isEven)
result(small_arr,a)

array([[False,  True, False,  True],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False]])

In [6]:
#5[2]
def amountOfEvenNumbers(a):
  count = 0
  if a % 2 == 0:
    count += 1
  return count
num_even = np.vectorize(amountOfEvenNumbers) (small_arr)
np.sum(num_even)

12

In [7]:
#6[2]
def squared(a):
  return a**2

squared_num = np.vectorize(squared) (a)
squared_num

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [8]:
#7[2]
diag = np.eye(10)
diag + arr

array([[  2.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  2.,   5.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.],
       [  3.,   6.,  10.,  12.,  15.,  18.,  21.,  24.,  27.,  30.],
       [  4.,   8.,  12.,  17.,  20.,  24.,  28.,  32.,  36.,  40.],
       [  5.,  10.,  15.,  20.,  26.,  30.,  35.,  40.,  45.,  50.],
       [  6.,  12.,  18.,  24.,  30.,  37.,  42.,  48.,  54.,  60.],
       [  7.,  14.,  21.,  28.,  35.,  42.,  50.,  56.,  63.,  70.],
       [  8.,  16.,  24.,  32.,  40.,  48.,  56.,  65.,  72.,  80.],
       [  9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  82.,  90.],
       [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 101.]])

In [9]:
#8[2]
a = np.arange(1,11)
aa = a[::-1]
b = np.arange(1,11)
bb = b[::-1]
arr_rev = np.multiply.outer(aa,bb) 
arr_rev

array([[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
       [ 90,  81,  72,  63,  54,  45,  36,  27,  18,   9],
       [ 80,  72,  64,  56,  48,  40,  32,  24,  16,   8],
       [ 70,  63,  56,  49,  42,  35,  28,  21,  14,   7],
       [ 60,  54,  48,  42,  36,  30,  24,  18,  12,   6],
       [ 50,  45,  40,  35,  30,  25,  20,  15,  10,   5],
       [ 40,  36,  32,  28,  24,  20,  16,  12,   8,   4],
       [ 30,  27,  24,  21,  18,  15,  12,   9,   6,   3],
       [ 20,  18,  16,  14,  12,  10,   8,   6,   4,   2],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [10]:
#9[2]
rand_float = 10 * np.random.random(size = (10,10)) 
rand_sort = np.sort(rand_float)
rand_sort

array([[2.5096477 , 2.85264285, 2.98288536, 4.68475398, 5.5331877 ,
        6.17395598, 7.48428887, 8.95426166, 9.51320675, 9.52911946],
       [0.011642  , 0.258106  , 3.19314052, 3.43187833, 5.07122608,
        7.33252187, 7.49265873, 8.1321732 , 9.67636763, 9.80977044],
       [0.03273543, 0.07658289, 1.29375018, 1.36518755, 2.06246069,
        2.29061668, 2.99712752, 4.54336722, 5.32503255, 5.43679802],
       [0.65905513, 1.4313361 , 2.2616107 , 2.85229127, 3.00363047,
        3.61849133, 6.29893862, 8.39735244, 8.55916491, 9.84202308],
       [2.95356243, 3.05376069, 3.87969727, 4.43445602, 5.08566617,
        5.23233371, 5.71944371, 7.34314741, 7.35539019, 9.228164  ],
       [0.84762342, 1.85003068, 1.86848378, 4.95937016, 5.75578885,
        6.57683131, 7.23411687, 7.31323243, 9.70359261, 9.84073464],
       [1.49774089, 2.55076416, 2.947499  , 3.38289078, 4.22067926,
        4.41537826, 6.6835516 , 7.27502505, 9.17959678, 9.65990359],
       [0.47005589, 0.97840889, 2.3852462

In [11]:
#10[2]
def find_mean(array):
  return np.mean(array)

growing = np.apply_along_axis(find_mean, 1, arr)
growing

array([ 5.5, 11. , 16.5, 22. , 27.5, 33. , 38.5, 44. , 49.5, 55. ])

In [12]:
#11[4]
array = np.random.randint(-100, 100, size=20)
def merge(array, left, right):
  a = np.partition(left, len(left)-1)
  b = np.partition(right, len(right)-1)
  arr = np.hstack([a, b])
  arr = np.partition(arr, np.arange(len(array)))
  return arr

def mergeSort(array):
  left, right = np.split(array, [2])
  if len(left) > 1 and len(right) > 1:
    mergeSort(left), mergeSort(right) 
  return merge(array, left, right)

print(mergeSort(array))

[-100  -95  -81  -74  -74  -74  -63  -60  -17   -8    9   15   39   41
   58   65   68   80   82   94]
